// Code generated by Wire protocol buffer compiler, do not edit.
// Source: android.emulation.control.ClipData in emulator_controller.proto
package com.android.emulator.control

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

/**
 * Representation of a clipped data object on the clipboard.
 */
class ClipData(
  /**
   * UTF-8 Encoded text.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  val text: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ClipData, ClipData.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.text = text
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ClipData) return false
    if (unknownFields != other.unknownFields) return false
    if (text != other.text) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + text.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """text=${sanitize(text)}"""
    return result.joinToString(prefix = "ClipData{", separator = ", ", postfix = "}")
  }

  fun copy(text: String = this.text, unknownFields: ByteString = this.unknownFields): ClipData =
      ClipData(text, unknownFields)

  class Builder : Message.Builder<ClipData, Builder>() {
    @JvmField
    var text: String = ""

    /**
     * UTF-8 Encoded text.
     */
    fun text(text: String): Builder {
      this.text = text
      return this
    }

    override fun build(): ClipData = ClipData(
      text = text,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ClipData> = object : ProtoAdapter<ClipData>(
      FieldEncoding.LENGTH_DELIMITED, 
      ClipData::class, 
      "type.googleapis.com/android.emulation.control.ClipData", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ClipData): Int {
        var size = value.unknownFields.size
        if (value.text != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.text)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ClipData) {
        if (value.text != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ClipData {
        var text: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> text = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ClipData(
          text = text,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ClipData): ClipData = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
