// Code generated by Wire protocol buffer compiler, do not edit.
// Source: android.emulation.control.ParameterValue in emulator_controller.proto
package com.android.emulator.control

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.checkElementsNotNull
import com.squareup.wire.internal.immutableCopyOf
import kotlin.Any
import kotlin.Boolean
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

class ParameterValue(
  data: List<Float> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ParameterValue, ParameterValue.Builder>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.PACKED
  )
  @JvmField
  val data: List<Float> = immutableCopyOf("data", data)

  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.data = data
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ParameterValue) return false
    if (unknownFields != other.unknownFields) return false
    if (data != other.data) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + data.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (data.isNotEmpty()) result += """data=$data"""
    return result.joinToString(prefix = "ParameterValue{", separator = ", ", postfix = "}")
  }

  fun copy(data: List<Float> = this.data, unknownFields: ByteString = this.unknownFields):
      ParameterValue = ParameterValue(data, unknownFields)

  class Builder : Message.Builder<ParameterValue, Builder>() {
    @JvmField
    var data: List<Float> = emptyList()

    fun data(data: List<Float>): Builder {
      checkElementsNotNull(data)
      this.data = data
      return this
    }

    override fun build(): ParameterValue = ParameterValue(
      data = data,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ParameterValue> = object : ProtoAdapter<ParameterValue>(
      FieldEncoding.LENGTH_DELIMITED, 
      ParameterValue::class, 
      "type.googleapis.com/android.emulation.control.ParameterValue", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ParameterValue): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.FLOAT.asPacked().encodedSizeWithTag(1, value.data)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ParameterValue) {
        ProtoAdapter.FLOAT.asPacked().encodeWithTag(writer, 1, value.data)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ParameterValue {
        val data = mutableListOf<Float>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> data.add(ProtoAdapter.FLOAT.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ParameterValue(
          data = data,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ParameterValue): ParameterValue = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
