// Code generated by Wire protocol buffer compiler, do not edit.
// Source: android.emulation.control.SensorValue in emulator_controller.proto
package com.android.emulator.control

import com.squareup.wire.EnumAdapter
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.WireField
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import kotlin.jvm.JvmStatic
import okio.ByteString

/**
 * A single sensor value.
 */
class SensorValue(
  /**
   * Type of sensor
   */
  @field:WireField(
    tag = 1,
    adapter = "com.android.emulator.control.SensorValue${'$'}SensorType#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  val target: SensorType = SensorType.ACCELERATION,
  /**
   * [Output Only]
   */
  @field:WireField(
    tag = 2,
    adapter = "com.android.emulator.control.SensorValue${'$'}State#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  val status: State = State.OK,
  /**
   * Value interpretation depends on sensor enum, will contain at most 3
   * values.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.android.emulator.control.ParameterValue#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  val value: ParameterValue? = null,
  unknownFields: ByteString = ByteString.EMPTY
) : Message<SensorValue, SensorValue.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.target = target
    builder.status = status
    builder.value = value
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is SensorValue) return false
    if (unknownFields != other.unknownFields) return false
    if (target != other.target) return false
    if (status != other.status) return false
    if (value != other.value) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + target.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + value.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """target=$target"""
    result += """status=$status"""
    if (value != null) result += """value=$value"""
    return result.joinToString(prefix = "SensorValue{", separator = ", ", postfix = "}")
  }

  fun copy(
    target: SensorType = this.target,
    status: State = this.status,
    value: ParameterValue? = this.value,
    unknownFields: ByteString = this.unknownFields
  ): SensorValue = SensorValue(target, status, value, unknownFields)

  class Builder : Message.Builder<SensorValue, Builder>() {
    @JvmField
    var target: SensorType = SensorType.ACCELERATION

    @JvmField
    var status: State = State.OK

    @JvmField
    var value: ParameterValue? = null

    /**
     * Type of sensor
     */
    fun target(target: SensorType): Builder {
      this.target = target
      return this
    }

    /**
     * [Output Only]
     */
    fun status(status: State): Builder {
      this.status = status
      return this
    }

    /**
     * Value interpretation depends on sensor enum, will contain at most 3
     * values.
     */
    fun value(value: ParameterValue?): Builder {
      this.value = value
      return this
    }

    override fun build(): SensorValue = SensorValue(
      target = target,
      status = status,
      value = value,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<SensorValue> = object : ProtoAdapter<SensorValue>(
      FieldEncoding.LENGTH_DELIMITED, 
      SensorValue::class, 
      "type.googleapis.com/android.emulation.control.SensorValue", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: SensorValue): Int {
        var size = value.unknownFields.size
        if (value.target != SensorType.ACCELERATION) size +=
            SensorType.ADAPTER.encodedSizeWithTag(1, value.target)
        if (value.status != State.OK) size += State.ADAPTER.encodedSizeWithTag(2, value.status)
        if (value.value != null) size += ParameterValue.ADAPTER.encodedSizeWithTag(3, value.value)
        return size
      }

      override fun encode(writer: ProtoWriter, value: SensorValue) {
        if (value.target != SensorType.ACCELERATION) SensorType.ADAPTER.encodeWithTag(writer, 1,
            value.target)
        if (value.status != State.OK) State.ADAPTER.encodeWithTag(writer, 2, value.status)
        if (value.value != null) ParameterValue.ADAPTER.encodeWithTag(writer, 3, value.value)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): SensorValue {
        var target: SensorType = SensorType.ACCELERATION
        var status: State = State.OK
        var value: ParameterValue? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> try {
              target = SensorType.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            2 -> try {
              status = State.ADAPTER.decode(reader)
            } catch (e: ProtoAdapter.EnumConstantNotFoundException) {
              reader.addUnknownField(tag, FieldEncoding.VARINT, e.value.toLong())
            }
            3 -> value = ParameterValue.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return SensorValue(
          target = target,
          status = status,
          value = value,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: SensorValue): SensorValue = value.copy(
        value = value.value?.let(ParameterValue.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  enum class State(
    override val value: Int
  ) : WireEnum {
    OK(0),

    /**
     * qemud service is not available/initiated.
     */
    NO_SERVICE(-3),

    /**
     * Sensor is disabled.
     */
    DISABLED(-2),

    /**
     * Unknown sensor (should not happen)
     */
    UNKNOWN(-1);

    companion object {
      @JvmField
      val ADAPTER: ProtoAdapter<State> = object : EnumAdapter<State>(
        State::class, 
        PROTO_3, 
        State.OK
      ) {
        override fun fromValue(value: Int): State? = State.fromValue(value)
      }

      @JvmStatic
      fun fromValue(value: Int): State? = when (value) {
        0 -> OK
        -3 -> NO_SERVICE
        -2 -> DISABLED
        -1 -> UNKNOWN
        else -> null
      }
    }
  }

  /**
   * These are the various sensors that can be available in an emulated
   * devices.
   */
  enum class SensorType(
    override val value: Int
  ) : WireEnum {
    /**
     * Measures the acceleration force in m/s2 that is applied to a device
     * on all three physical axes (x, y, and z), including the force of
     * gravity.
     */
    ACCELERATION(0),

    /**
     * Measures a device's rate of rotation in rad/s around each of the
     * three physical axes (x, y, and z).
     */
    GYROSCOPE(1),

    /**
     * Measures the ambient geomagnetic field for all three physical axes
     * (x, y, z) in μT.
     */
    MAGNETIC_FIELD(2),

    /**
     * Measures degrees of rotation that a device makes around all three
     * physical axes (x, y, z)
     */
    ORIENTATION(3),

    /**
     * Measures the temperature of the device in degrees Celsius (°C).
     */
    TEMPERATURE(4),

    /**
     * Measures the proximity of an object in cm relative to the view screen
     * of a device. This sensor is typically used to determine whether a
     * handset is being held up to a person's ear.
     */
    PROXIMITY(5),

    /**
     * Measures the ambient light level (illumination) in lx.
     */
    LIGHT(6),

    /**
     * Measures the ambient air pressure in hPa or mbar.
     */
    PRESSURE(7),

    /**
     * Measures the relative ambient humidity in percent (%).
     */
    HUMIDITY(8),

    MAGNETIC_FIELD_UNCALIBRATED(9),

    GYROSCOPE_UNCALIBRATED(10);

    companion object {
      @JvmField
      val ADAPTER: ProtoAdapter<SensorType> = object : EnumAdapter<SensorType>(
        SensorType::class, 
        PROTO_3, 
        SensorType.ACCELERATION
      ) {
        override fun fromValue(value: Int): SensorType? = SensorType.fromValue(value)
      }

      @JvmStatic
      fun fromValue(value: Int): SensorType? = when (value) {
        0 -> ACCELERATION
        1 -> GYROSCOPE
        2 -> MAGNETIC_FIELD
        3 -> ORIENTATION
        4 -> TEMPERATURE
        5 -> PROXIMITY
        6 -> LIGHT
        7 -> PRESSURE
        8 -> HUMIDITY
        9 -> MAGNETIC_FIELD_UNCALIBRATED
        10 -> GYROSCOPE_UNCALIBRATED
        else -> null
      }
    }
  }
}
