// Code generated by Wire protocol buffer compiler, do not edit.
// Source: waterfall.ForwardedSessions in waterfall.proto
package com.google.waterfall

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.checkElementsNotNull
import com.squareup.wire.internal.immutableCopyOf
import com.squareup.wire.internal.redactElements
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.collections.List
import kotlin.jvm.JvmField
import okio.ByteString

class ForwardedSessions(
  sessions: List<ForwardSession> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY
) : Message<ForwardedSessions, ForwardedSessions.Builder>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 1,
    adapter = "com.google.waterfall.ForwardSession#ADAPTER",
    label = WireField.Label.REPEATED
  )
  @JvmField
  val sessions: List<ForwardSession> = immutableCopyOf("sessions", sessions)

  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.sessions = sessions
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ForwardedSessions) return false
    if (unknownFields != other.unknownFields) return false
    if (sessions != other.sessions) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + sessions.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (sessions.isNotEmpty()) result += """sessions=$sessions"""
    return result.joinToString(prefix = "ForwardedSessions{", separator = ", ", postfix = "}")
  }

  fun copy(sessions: List<ForwardSession> = this.sessions, unknownFields: ByteString =
      this.unknownFields): ForwardedSessions = ForwardedSessions(sessions, unknownFields)

  class Builder : Message.Builder<ForwardedSessions, Builder>() {
    @JvmField
    var sessions: List<ForwardSession> = emptyList()

    fun sessions(sessions: List<ForwardSession>): Builder {
      checkElementsNotNull(sessions)
      this.sessions = sessions
      return this
    }

    override fun build(): ForwardedSessions = ForwardedSessions(
      sessions = sessions,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<ForwardedSessions> = object : ProtoAdapter<ForwardedSessions>(
      FieldEncoding.LENGTH_DELIMITED, 
      ForwardedSessions::class, 
      "type.googleapis.com/waterfall.ForwardedSessions", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: ForwardedSessions): Int {
        var size = value.unknownFields.size
        size += ForwardSession.ADAPTER.asRepeated().encodedSizeWithTag(1, value.sessions)
        return size
      }

      override fun encode(writer: ProtoWriter, value: ForwardedSessions) {
        ForwardSession.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.sessions)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): ForwardedSessions {
        val sessions = mutableListOf<ForwardSession>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> sessions.add(ForwardSession.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ForwardedSessions(
          sessions = sessions,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: ForwardedSessions): ForwardedSessions = value.copy(
        sessions = value.sessions.redactElements(ForwardSession.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
