// Code generated by Wire protocol buffer compiler, do not edit.
// Source: waterfall.PortForwarder in waterfall.proto
package com.google.waterfall

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Unit

/**
 * PortForwarder service runs a port forwarding session via waterfall.
 * It allows start and stop forwarding connections when the waterfall client
 * is unable to mantains any state (e.g. the waterfall adb binary).
 */
interface PortForwarderClient : Service {
  fun ForwardPort(): GrpcCall<PortForwardRequest, Unit>

  fun Stop(): GrpcCall<PortForwardRequest, Unit>

  fun StopAll(): GrpcCall<Unit, Unit>

  fun List(): GrpcCall<Unit, ForwardedSessions>
}
