// Code generated by Wire protocol buffer compiler, do not edit.
// Source: waterfall.VersionMessage in waterfall.proto
package com.google.waterfall

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.internal.sanitize
import kotlin.Any
import kotlin.Boolean
import kotlin.Int
import kotlin.Long
import kotlin.String
import kotlin.hashCode
import kotlin.jvm.JvmField
import okio.ByteString

class VersionMessage(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY
  )
  @JvmField
  val version: String = "",
  unknownFields: ByteString = ByteString.EMPTY
) : Message<VersionMessage, VersionMessage.Builder>(ADAPTER, unknownFields) {
  override fun newBuilder(): Builder {
    val builder = Builder()
    builder.version = version
    builder.addUnknownFields(unknownFields)
    return builder
  }

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is VersionMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (version != other.version) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + version.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """version=${sanitize(version)}"""
    return result.joinToString(prefix = "VersionMessage{", separator = ", ", postfix = "}")
  }

  fun copy(version: String = this.version, unknownFields: ByteString = this.unknownFields):
      VersionMessage = VersionMessage(version, unknownFields)

  class Builder : Message.Builder<VersionMessage, Builder>() {
    @JvmField
    var version: String = ""

    fun version(version: String): Builder {
      this.version = version
      return this
    }

    override fun build(): VersionMessage = VersionMessage(
      version = version,
      unknownFields = buildUnknownFields()
    )
  }

  companion object {
    @JvmField
    val ADAPTER: ProtoAdapter<VersionMessage> = object : ProtoAdapter<VersionMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      VersionMessage::class, 
      "type.googleapis.com/waterfall.VersionMessage", 
      PROTO_3, 
      null
    ) {
      override fun encodedSize(value: VersionMessage): Int {
        var size = value.unknownFields.size
        if (value.version != "") size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.version)
        return size
      }

      override fun encode(writer: ProtoWriter, value: VersionMessage) {
        if (value.version != "") ProtoAdapter.STRING.encodeWithTag(writer, 1, value.version)
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): VersionMessage {
        var version: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> version = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return VersionMessage(
          version = version,
          unknownFields = unknownFields
        )
      }

      override fun redact(value: VersionMessage): VersionMessage = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
