// Code generated by Wire protocol buffer compiler, do not edit.
// Source: waterfall.Waterfall in waterfall.proto
package com.google.waterfall

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcStreamingCall
import com.squareup.wire.Service
import kotlin.Unit

interface WaterfallClient : Service {
  /**
   * Echo exists solely for test purposes.
   */
  fun Echo(): GrpcStreamingCall<Message, Message>

  /**
   * Push file/dir from host to device.
   */
  fun Push(): GrpcStreamingCall<Transfer, Transfer>

  /**
   * Pull file/dir from device to host.
   */
  fun Pull(): GrpcStreamingCall<Transfer, Transfer>

  /**
   * Exec executes cmd in the device and forward stdout and stderr to client
   * Exec expects a single initial CmdProgress message if stdin is not
   * being redirected. Otherwise Exec will read std from the stream.
   */
  fun Exec(): GrpcStreamingCall<CmdProgress, CmdProgress>

  /**
   * Forward forwards the stream payload to the requested socket
   */
  fun Forward(): GrpcStreamingCall<ForwardMessage, ForwardMessage>

  /**
   * Version gets the version of the server.
   */
  fun Version(): GrpcCall<Unit, VersionMessage>
}
