name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '21'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: ./gradlew check

      - name: Show Reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: reports-${{ runner.os }}
          path: build/
